'use strict'
const test = require('tap').test
const wordcount = require('../word-count.js')

test('word-count', t => {
  t.is(wordcount('This is a test'), 4, 'plain text')
  t.is(wordcount('now with 23 a number'), 5, 'integer')
  t.is(wordcount('now with 23.17'), 3, 'decimal')
  t.is(wordcount("emoji 😍😍 do not count"), 4, 'emoji')
  t.is(wordcount("possessive's are one word"), 4, 'possessive')
  t.is(wordcount('possessive’s are one word'), 4, 'possessive unicode')
  t.is(wordcount('some "quoted text" does not impact'), 6, 'quotes')
  t.is(wordcount("also 'single quotes' are ok"), 5, 'single quotes')
  t.is(wordcount("don't do contractions"), 3, 'contractions count as a single word')
  t.is(wordcount('hyphenated words-are considered whole'), 4, 'hyphenated words')
  t.is(wordcount('underbars are_too just one'), 4, 'underbars')
  t.is(wordcount('n-dash ranges 1–3 are NOT'), 6, 'en-dash')
  t.is(wordcount('m-dash connected—bits also are not'), 6, 'em-dash')
  t.is(wordcount('abc/def'), 2, 'slashed')
  t.is(wordcount('abc\\def'), 2, 'back-slashed')
  t.is(wordcount('cheap--endash'), 2, 'cheap en-dash')
  t.is(wordcount('cheap---emdash'), 2, 'cheap em-dash')
  t.is(wordcount('soft­hyphen'), 1, 'soft hyphen')
  t.is(wordcount('The quick (“brown”) fox can’t jump 32.3 feet, right?'), 9, 'tr29 example')
  t.is(wordcount('true‐hyphen'), 1, 'true hyphenated words')
  t.is(wordcount('nonbreaking‑hyphen'), 1, 'non-breaking hyphen')
  t.done()
})